build update

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,34 +1,94 @@
 #!/bin/bash
 
 GREEN="\e[32m"
+RED="\e[31m"
 END_COLOR="\e[0m"
 venv='virtual_enviroment'
+database_file='database/database.db'
+
+function usage {
+    echo "Usage: $0 [option]"
+
+    echo 'List of options:
+    
+         -h: Display the help message
+         -c: Create database engine'
+}
+
+function all {
+    #CREATE VIRTUAL ENVIROMENT
+    echo -e "${GREEN}Creating virtual enviroment...${END_COLOR}"
+    sleep 3
+    python3 -m venv $venv
+    echo -e "${GREEN}$venv created.${END_COLOR}"
+
+    echo
+
+    #INSTALL DEPENDENCIES
+
+    echo -e "${GREEN}Installing dependencies...${END_COLOR}"
+    sleep 3
+    . $venv/bin/activate
+    echo -e "${GREEN}Upgrading pip command...${END_COLOR}"
+    python -m pip install --upgrade pip
+    pip install -r requirements.txt
+    if [ $? -ne 0]; then
+        echo -e "${RED}Installation failed.${END_COLOR}"
+        exit 1
+    else
+        echo -e "${GREEN}All dependencies installed.${END_COLOR}"
+    fi
+
+    echo
+
+    create_database_engine
+}
+
+function create_database_engine {
+    #CREATE DATABASE ENGINE
+
+    echo -e "${GREEN}Creating database engine...${END_COLOR}"
+    sleep 3
+    if [ -f "$database_file" ]; then
+        echo -e "${GREEN}Database engine already created.${END_COLOR}"
+    else
+        python3 -c "from database.db import create_database; create_database()"
+        echo -e "${GREEN}Database engine created.${END_COLOR}"
+    fi
+}
+
+function header {
+    echo ' __  /   __   \                                                   
+|__)(   /  \|_ ) _ _ _ _  _  _ |  |.|_  _ _  _    |_    .| _| _ _ 
+|    \\/\_\/|_/ (-| _)(_)| )(_||  |||_)| (_|| \/  |_)|_|||(_|(-|  
+      /                                       /                   
+
+'
+}
 
 clear
+header
 
-#CREATE VIRTUAL ENVIROMENT
-echo -e "${GREEN}Creating virtual enviroment...${END_COLOR}"
-sleep 3
-python3 -m venv $venv
-echo -e "${GREEN}$venv created.${END_COLOR}"
+while getopts "hc" opt; do
+    case ${opt} in
+        h )
+            usage
+            ;;
+        c )
+            if [ -z "$VIRTUAL_ENV" ]; then
+                echo -e "${RED}You must activate the virtual enviroment.${END_COLOR}"
+                exit 1
+            fi
+            create_database_engine
+            ;;
+        * )
+            usage
+            exit 1
+            ;;
+    esac
+done
 
-echo
-
-#INSTALL DEPENDENCIES
-
-echo -e "${GREEN}Installing dependencies...${END_COLOR}"
-sleep 3
-. $venv/bin/activate
-echo -e "${GREEN}Upgrading pip command...${END_COLOR}"
-python -m pip install --upgrade pip
-pip install -r requirements.txt
-echo -e "${GREEN}All dependencies installed.${END_COLOR}"
-
-echo
-
-#CREATE DATABASE ENGINE
-
-echo -e "${GREEN}Creating database engine...${END_COLOR}"
-sleep 3
-python3 -c "from database.db import create_database; create_database()"
-echo -e "${GREEN}Database engine created.${END_COLOR}"
+if [ $OPTIND -eq 1 ]; then
+    all
+    exit 0
+fi
